#+title: Dotfiles
#+author: Luis Victoria

/My dotfile configuration/

* Getting started
#+begin_src sh
git clone https://github.com/LV/dotfiles.git ~/.config
cd ~/.config/
./install.sh
#+end_src

If you have a ~permission denied~ error, just do:
#+begin_src shell
chmod u+x install.sh
#+end_src

*NOTE*: Make sure that you backup your ~.zshrc~ file; you will need to  replace it with this configuration
#+begin_src shell
ln -s ~/.config/.zshrc ~/.zshrc
#+end_src

* Requirements
To get the full functionality of this configuration, you are going to need:
 - ~cmake~
 - ~libvterm~

You can get away with not installing these, but you could run into problems down the line

** Additional installations
To get the full configuration working, you're going to need to install additional items:

#+begin_src shell
npm install -g pyright
#+end_src

*** Font
The font I use is /Inconsolata LGC Nerd Font/ since it includes italics (download [[https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/InconsolataLGC.zip][here]])

If you're on WSL, here are the following instructions
1. Extract the zip file, right click and install for all users
2. Open WSL and go to the ~$HOME~ directory
3. Create a =~/.fonts/= directory if it doesn't exist
4. Copy all /Inconsolata LGC/ fonts into the =~/.fonts/= directory:
   #+begin_src shell
cp /mnt/c/Windows/Fonts/InconsolataLGC* ~/.fonts
   #+end_src

   You should type this out instead of copying the command, after typing the ~*~ character, hit *TAB* to autocomplete and get a list of all the appropriate fonts
5. Run:
   #+begin_src shell
fc-cache -fv
   #+end_src
6. Make sure the fonts are properly loaded into WSL:
   #+begin_src shell
fc-list | grep "InconsolataLGC"
   #+end_src
   and you should see multiple fonts

* Troubleshooting
** When launching Emacs, I do not have your config loaded!
Emacs loads ~init.el~ in the following preference (see [[https://www.gnu.org/software/emacs/manual/html_mode/emacs/Find-Init.html][more info]]):
1. =~/.emacs.el=
2. =~/.emacs=
3. =~/.emacs.d/init=
4. =~/.config/emacs= (or ~$XDG_CONFIG_HOME~)


Check to see if the first three locations exist, and remove them if so.

** Upon launching Emacs, no window appears!
Sometimes, you need to install additional modules within Emacs and this leads to weird things such as no window appearing. Simply launch Emacs with the following:

#+begin_src shell
emacs --debut-init
#+end_src

*NOTE*: This problem was seen on my M1 MacBookPro (see [[https://github.com/LV/dotfiles/commit/1dd1a79af6a27f9103d4c39bdbea04fde2535e0b#commitcomment-124109384][here]])
