# set main prefix
set -g prefix C-Space

set -g default-terminal "screen-256color"  # set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc"  # override to enable true-color for compatible terminals

set -g set-clipboard on       # use system clipboard
set -g history-limit 1000000  # increase size history (from 2,000)
set -g mouse on               # enable mouse support
set -g status-interval 3      # update status line every 3 seconds (from 15)

set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi

set -gq allow-passthrough on  # allow programs to bypass tmux (e.g. image.nvim)
set -g visual-activity off

bind c new-window -c "#{pane_current_path}"  # new window in same path

set -g @tmux-dotbar-fg "#0B0E14"
set -g @tmux-dotbar-bg "#475266"
set -g @tmux-dotbar-fg-current "#BFBDB6"
set -g @tmux-dotbar-fg-session "#565B66"
set -g @tmux-dotbar-fg-prefix "#95E6CB"
set -g @tmux-dotbar-position "bottom"
set -g @tmux-dotbar-justify "absolute-centre"
set -g @tmux-dotbar-left "true"
set -g @tmux-dotbar-status-left "#S"
set -g @tmux-dotbar-right "false"
set -g @tmux-dotbar-status-right "%H:%M"
set -g @tmux-dotbar-window-status-format " #W "
set -g @tmux-dotbar-window-status-separator " • "
set -g @tmux-dotbar-maximized-icon "󰊓"
set -g @tmux-dotbar-show-maximized-icon-for-all-tabs false
set -g @tmux-dotbar-bold-status true
set -g @tmux-dotbar-bold-current-window false
set -g @tmux-dotbar-ssh-enabled true
set -g @tmux-dotbar-ssh-icon '󰌘'
set -g @tmux-dotbar-ssh-icon-only false

run-shell ~/.config/tmux/plugins/dotbar.tmux
