name: 'Sync Dotfile Submodules'

on:
  workflow_dispatch:
  repository_dispatch:
    types: [submodule_update]

jobs:
  sync:
    name: 'Sync Dotfile Submodules'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
        fetch-depth: 0  # Ensure the entire history is fetched

    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git add .
        git commit -m "Auto updated submodule references" || echo "No changes to commit"
        git push origin HEAD:${GITHUB_REF#refs/heads/}

